# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-04 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskdashapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controls',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='riskdashapp.Control_Owners'),
            preserve_default=False,
        ),
    ]
