# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskdashapp', '0002_controls_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_owners',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='control_status',
            name='label',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='controls',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
