# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-07 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskdashapp', '0003_auto_20160606_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='type_of_risk',
            field=models.ManyToManyField(to='riskdashapp.Risk_type'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
