# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-09 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskdashapp', '0005_auto_20160608_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controls',
            old_name='type',
            new_name='type_of_control',
        ),
    ]
