# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-09 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskdashapp', '0006_auto_20160609_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
