# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-09 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskdashapp', '0007_riskadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiskAdmin',
        ),
    ]
