# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-10 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskdashapp', '0008_delete_riskadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='Score',
        ),
    ]
